version: '3'
services:
    postgres:
      image: postgres
      # environment:
      #   POSTGRES_PASSWORD: secret
      volumes:
        - /opt/data/apolo/opendata/pgdata:/var/lib/postgresql/data
        - ./init/:/docker-entrypoint-initdb.d/
        # - /etc/localtime:/etc/localtime:ro
      ports:
        - 9555:5432
      networks:
        - opendata_net
      environment:
        - POSTGRES_INITDB_ARGS="-A trust"
      env_file: pgsecrets.env
    es:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
      env_file: .env
      environment:
        - cluster.name=es
        - bootstrap.memory_lock=true
        - node.name=es
        # - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        # sysctl -wp vm.max_map_count=262144
        - cluster.initial_master_nodes=es
        #- discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
        - "discovery.zen.ping.unicast.hosts=es"
        - http.cors.enabled=true
        - http.cors.allow-origin=*
        - ELASTICSEARCH_USERNAME=elastic
        - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
        # - xpack.security.enabled=$ELASTIC_SECURITY
        # - xpack.security.transport.ssl.enabled=true
        - network.host=_eth0_
      ulimits:
          memlock:
              soft: -1
              hard: -1
      volumes:
        # sudo chown 1000:1000 <directory you wish to mount>
        - /opt/data/apolo/opendata/esdata:/usr/share/elasticsearch/data
        # - /etc/localtime:/etc/localtime:ro
      ports:
        - 9200:9200
      networks:
        - opendata_net
    kibana:
      image: docker.elastic.co/kibana/kibana:7.9.3
      env_file: .env
      environment:
          - ELASTICSEARCH_URL=http://es:9200
          - ELASTICSEARCH_USERNAME=elastic
          - ELASTICSEARCH_PASSWORD-changeme
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
      ports:
          - 5666:5601
      depends_on: ['es']
      networks:
        - opendata_net
    metabase:
      image: metabase/metabase
      ports:
        - 3001:3000
      networks:
        - opendata_net
networks:
  opendata_net:
    driver: bridge
    ipam:
      driver: default

# volumes:
#     db_data:
#     postgres_data:
#     esdata:
#         driver: local
